grasp

In [30]:
import genesis as gs
import numpy as np
import torch
from pytransform3d import (
    transformations as pt,
    rotations as pr,
    batch_rotations as pb,
    trajectories as ptr,
    plot_utils as ppu
)

In [2]:
gs.init(backend=gs.gpu, seed=42)

[Genesis] [11:09:32] [INFO] ╭───────────────────────────────────────────────╮
[Genesis] [11:09:32] [INFO] │┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈ Genesis ┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈│
[Genesis] [11:09:32] [INFO] ╰───────────────────────────────────────────────╯
[Genesis] [11:09:32] [INFO] Running on [NVIDIA GeForce RTX 3070 Laptop GPU] with backend gs.cuda. Device memory: 7.78 GB.
[Genesis] [11:09:32] [INFO] 🚀 Genesis initialized. 🔖 version: 0.2.1, 🌱 seed: 42, 📏 precision: '32', 🐛 debug: False, 🎨 theme: 'dark'.


In [13]:

scene = gs.Scene(
    show_viewer = True,
    viewer_options = gs.options.ViewerOptions(
        res           = (1280, 960),
        camera_pos    = (3.5, 0.0, 2.5),
        camera_lookat = (0.0, 0.0, 0.5),
        camera_fov    = 40,
        max_FPS       = 60,
    ),
    sim_options=gs.options.SimOptions(
        dt = 0.01,
    ),
    vis_options = gs.options.VisOptions(
        show_world_frame = True,
        world_frame_size = 1.0,
        show_link_frame  = False,
        show_cameras     = False,
        plane_reflection = True,
        ambient_light    = (0.1, 0.1, 0.1),
    ),
    renderer=gs.renderers.Rasterizer(),
)

plane = scene.add_entity(
    gs.morphs.Plane(),
)
franka = scene.add_entity(
    gs.morphs.MJCF(file='xml/franka_emika_panda/panda.xml'),
)
cube_size = (0.1, 0.07, 0.03)
cube_pos = (0.7, 0, 0.015)
cube = scene.add_entity(
    gs.morphs.Box(
        size = cube_size,
        pos  = cube_pos,
    )
)


cam = scene.add_camera(
    res    = (640, 480),
    pos    = (3.5, 0.0, 2.5),
    lookat = (0, 0, 0.5),
    fov    = 30,
    GUI    = False,
)


[Genesis] [12:39:34] [INFO] Scene <bf3aae3> created.
[Genesis] [12:39:34] [INFO] Adding <gs.RigidEntity>. idx: 0, uid: <c2047b4>, morph: <gs.morphs.Plane>, material: <gs.materials.Rigid>.
[Genesis] [12:39:34] [INFO] Adding <gs.RigidEntity>. idx: 1, uid: <7e0a4a5>, morph: <gs.morphs.MJCF(file='/home/vahid/envs/panda/panda/lib/python3.10/site-packages/genesis/assets/xml/franka_emika_panda/panda.xml')>, material: <gs.materials.Rigid>.
[Genesis] [12:39:34] [WARNING] (MJCF) Tendon not supported
[Genesis] [12:39:34] [WARNING] (MJCF) Approximating tendon by joint actuator for `finger_joint1`
[Genesis] [12:39:34] [WARNING] (MJCF) Actuator control gain and bias parameters cannot be reduced to a unique PD control position gain. Using max between gain and bias.
[Genesis] [12:39:34] [WARNING] (MJCF) Approximating tendon by joint actuator for `finger_joint2`
[Genesis] [12:39:34] [WARNING] (MJCF) Actuator control gain and bias parameters cannot be reduced to a unique PD control position gain. Using 

In [14]:

scene.build()
motors_dof = np.arange(7)
fingers_dof = np.arange(7, 9)

# set control gains
# Note: the following values are tuned for achieving best behavior with Franka
# Typically, each new robot would have a different set of parameters.
# Sometimes high-quality URDF or XML file would also provide this and will be parsed.
franka.set_dofs_kp(
    np.array([4500, 4500, 3500, 3500, 2000, 2000, 2000, 100, 100]),
)
franka.set_dofs_kv(
    np.array([450, 450, 350, 350, 200, 200, 200, 10, 10]),
)
franka.set_dofs_force_range(
    np.array([-87, -87, -87, -87, -12, -12, -12, -100, -100]),
    np.array([ 87,  87,  87,  87,  12,  12,  12,  100,  100]),
)

# render rgb, depth, segmentation, and normal
# rgb, depth, segmentation, normal = cam.render(rgb=True, depth=True, segmentation=True, normal=True)


[Genesis] [12:39:48] [INFO] Building scene <bf3aae3>...
[Genesis] [12:39:50] [WARNING] Reference robot position exceeds joint limits.
[Genesis] [12:39:50] [WARNING] Constraint solver time constant was increased to avoid numerical instability (from `0.005` to `0.02`). Decrease simulation timestep to avoid altering the original value.


[W 05/01/25 12:39:52.071 10500] [frontend_ir.cpp:begin_frontend_struct_for_on_external_tensor@1694] ti.loop_config(serialize=True) does not have effect on the struct for. The execution order is not guaranteed.


[Genesis] [12:39:58] [INFO] Compiling simulation kernels...
[Genesis] [12:41:29] [INFO] Building visualizer...
[Genesis] [12:41:30] [INFO] Viewer created. Resolution: 1280×960, max_FPS: 60.


In [46]:
cube_qpos = np.concatenate((np.array(cube_pos), np.array([1, 0, 0, 0])), axis=0)

In [55]:
cube.set_qpos(cube_qpos)
qr = np.array([0.0000, -0.3002, 0.0000, -2.1991, 0.0000, 2.0071, 0.7854, 0.04, 0.04])

franka.ready_qpos = qr
franka.set_qpos(franka.ready_qpos)
scene.step()

[Genesis] [13:59:19] [INFO] Running at 0.01 FPS.


In [41]:
end_effector = franka.get_link('hand')
left_finger = franka.get_link('left_finger')
right_finger = franka.get_link('right_finger')

left_finger.get_pos(), right_finger.get_pos(), end_effector.get_pos()

(tensor([-0.5071, -0.0801,  0.9848], device='cuda:0'),
 tensor([-0.5075, -0.0805,  0.9832], device='cuda:0'),
 tensor([-0.5095, -0.0234,  0.9709], device='cuda:0'))

In [68]:

# get the end-effector link
end_effector = franka.get_link('hand')
above_box = cube.get_pos().cpu().numpy() + np.array([-cube_size[0]/2 + 0.02, 0, 0.11 + 0.1])
# move to pre-grasp pose
qpos = franka.inverse_kinematics(
    link = end_effector,
    pos  = above_box,
    quat = np.array([0, 1, 0, 0]),
)
# gripper open pos
qpos[-2:] = 0.04
path = franka.plan_path(
    qpos_goal     = qpos,
    num_waypoints = 200, # 2s duration
)

[Genesis] [14:05:35] [INFO] Path solution found successfully.


In [69]:
# execute the planned path
for waypoint in path:
    franka.control_dofs_position(waypoint)
    scene.step()

# allow robot to reach the last waypoint
for i in range(100):
    scene.step()


[Genesis] [14:05:39] [INFO] Running at 1.69 FPS.
[Genesis] [14:05:39] [INFO] Running at 1.77 FPS.
[Genesis] [14:05:39] [INFO] Running at 1.86 FPS.
[Genesis] [14:05:39] [INFO] Running at 1.96 FPS.
[Genesis] [14:05:39] [INFO] Running at 2.06 FPS.
[Genesis] [14:05:39] [INFO] Running at 2.16 FPS.
[Genesis] [14:05:39] [INFO] Running at 2.27 FPS.
[Genesis] [14:05:39] [INFO] Running at 2.39 FPS.
[Genesis] [14:05:39] [INFO] Running at 2.51 FPS.
[Genesis] [14:05:39] [INFO] Running at 2.63 FPS.
[Genesis] [14:05:39] [INFO] Running at 2.76 FPS.
[Genesis] [14:05:39] [INFO] Running at 2.90 FPS.
[Genesis] [14:05:39] [INFO] Running at 3.05 FPS.
[Genesis] [14:05:39] [INFO] Running at 3.20 FPS.
[Genesis] [14:05:39] [INFO] Running at 3.35 FPS.
[Genesis] [14:05:39] [INFO] Running at 3.52 FPS.
[Genesis] [14:05:39] [INFO] Running at 3.69 FPS.
[Genesis] [14:05:40] [INFO] Running at 3.87 FPS.
[Genesis] [14:05:40] [INFO] Running at 4.06 FPS.
[Genesis] [14:05:40] [INFO] Running at 4.26 FPS.
[Genesis] [14:05:40]

In [70]:
side_box = above_box + np.array([0.0, 0.0, -0.1])


# reach
qpos_reach = franka.inverse_kinematics(
    link = end_effector,
    pos  = side_box,
    quat = np.array([0, 1, 0, 0]),
)
path = franka.plan_path(
    qpos_goal     = qpos_reach,
    num_waypoints = 100, # 1s duration
)

for waypoint in path:
    franka.control_dofs_position(waypoint)
    scene.step()

# allow robot to reach the last waypoint
for i in range(100):
    scene.step()

[Genesis] [14:08:21] [INFO] Path solution found successfully.
[Genesis] [14:08:21] [INFO] Running at 0.13 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.13 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.14 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.15 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.16 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.17 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.17 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.18 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.19 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.20 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.21 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.22 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.24 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.25 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.26 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.28 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.29 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.31 FPS.
[Genesis] [14:08:21] [INFO] Running at 0.32 FPS.
[Genesi

In [71]:



# grasp
franka.control_dofs_position(qpos_reach[:-2], motors_dof)
franka.control_dofs_force(np.array([-0.5, -0.5]), fingers_dof)

for i in range(100):
    scene.step()


[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.00 FPS.
[Genesis] [16:50:51] [INFO] Running at 0.01 FPS.
[Genesis] [16:50:52] [INFO] Running at 0.01 FPS.
[Genesis] [16:50:52]

In [ ]:

# lift
qpos = franka.inverse_kinematics(
    link=end_effector,
    pos=np.array([0.65, 0.0, 0.28]),
    quat=np.array([0, 1, 0, 0]),
)
franka.control_dofs_position(qpos[:-2], motors_dof)
for i in range(200):
    scene.step()

In [21]:
# open
qpos = franka.inverse_kinematics(
    link=end_effector,
    pos=np.array([0.65, 0.0, 0.28]),
    quat=np.array([0, 1, 0, 0]),
)

franka.control_dofs_position(qpos[:-2], motors_dof)
franka.control_dofs_force(np.array([0, 0]), fingers_dof)
for i in range(100):
    scene.step()
# allow robot to reach the last waypoint
for i in range(100):
    scene.step()

[Genesis] [20:51:35] [INFO] Running at 0.32 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.34 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.36 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.37 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.39 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.41 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.44 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.46 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.48 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.51 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.53 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.56 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.59 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.62 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.66 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.69 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.73 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.76 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.80 FPS.
[Genesis] [20:51:36] [INFO] Running at 0.84 FPS.
[Genesis] [20:51:36]

[Genesis] [21:31:10] [INFO] Running at 0.06 FPS.


In [24]:
franka.get_dofs_force()

tensor([-0.0103,  0.0048,  0.0108, -0.0005, -0.0040, -0.0004, -0.0068,  0.0004,
        -0.0004], device='cuda:0')

In [39]:
cube_pos = cube.get_pos().cpu().numpy()
cube_quat = cube.get_quat().cpu().numpy()

cube_pos, cube_quat

(array([6.4999902e-01, 2.9570606e-06, 1.9892190e-02], dtype=float32),
 array([-1.3834608e-06,  9.9999994e-01,  4.4306205e-05,  7.9489763e-07],
       dtype=float32))

In [41]:
cube_pos = cube.get_pos().cpu().numpy()
cube_quat = cube.get_quat().cpu().numpy()

qpos = franka.inverse_kinematics(
    link=end_effector,
    pos=cube_pos + np.array([0, 0, 0.3]),
    quat=np.array([0, 1, 0, 0]),
)

franka.control_dofs_position(qpos[:-2], motors_dof)
franka.control_dofs_force(np.array([0, 0]), fingers_dof)
for i in range(100):
    scene.step()
# allow robot to reach the last waypoint
for i in range(100):
    scene.step()

[Genesis] [00:14:45] [INFO] Running at 0.28 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.29 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.31 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.32 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.34 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.36 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.38 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.40 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.42 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.44 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.46 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.48 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.51 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.54 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.56 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.59 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.63 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.66 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.69 FPS.
[Genesis] [00:14:45] [INFO] Running at 0.73 FPS.
[Genesis] [00:14:46]

In [ ]:

cam.start_recording()
import numpy as np

for i in range(120):
    scene.step()
    cam.set_pose(
        pos    = (3.0 * np.sin(i / 60), 3.0 * np.cos(i / 60), 2.5),
        lookat = (0, 0, 0.5),
    )
    cam.render()
cam.stop_recording(save_to_filename='video.mp4', fps=60)