grasp

In [1]:
import genesis as gs
import numpy as np
import torch
from pytransform3d import (
    transformations as pt,
    rotations as pr,
    batch_rotations as pb,
    trajectories as ptr,
    plot_utils as ppu
)

In [2]:
gs.init(backend=gs.cpu, seed=42)

[Genesis] [10:33:02] [INFO] ╭───────────────────────────────────────────────╮
[Genesis] [10:33:02] [INFO] │┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈ Genesis ┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈│
[Genesis] [10:33:02] [INFO] ╰───────────────────────────────────────────────╯
[Genesis] [10:33:05] [INFO] Running on [13th Gen Intel(R) Core(TM) i7-13800H] with backend gs.cpu. Device memory: 31.59 GB.
[Genesis] [10:33:05] [INFO] 🚀 Genesis initialized. 🔖 version: 0.2.1, 🌱 seed: 42, 📏 precision: '32', 🐛 debug: False, 🎨 theme: 'dark'.


In [3]:

scene = gs.Scene(
    show_viewer = True,
    viewer_options = gs.options.ViewerOptions(
        res           = (1280, 960),
        camera_pos    = (3.5, 0.0, 2.5),
        camera_lookat = (0.0, 0.0, 0.5),
        camera_fov    = 40,
        max_FPS       = 60,
    ),
    sim_options=gs.options.SimOptions(
        dt = 0.01,
    ),
    vis_options = gs.options.VisOptions(
        show_world_frame = True,
        world_frame_size = 1.0,
        show_link_frame  = False,
        show_cameras     = False,
        plane_reflection = True,
        ambient_light    = (0.1, 0.1, 0.1),
    ),
    renderer=gs.renderers.Rasterizer(),
)

plane = scene.add_entity(
    gs.morphs.Plane(),
)
franka = scene.add_entity(
    gs.morphs.MJCF(file='xml/franka_emika_panda/panda.xml'),
)
cube_size = (0.1, 0.07, 0.03)
cube_pos = (0.7, 0, 0.015)

cube = scene.add_entity(
    gs.morphs.Box(
        size = cube_size,
        pos  = cube_pos,
    ),
    # surface=gs.textures.ColorTexture(
    #     color = (0.8, 0.1 , 0.1),
    # ),
)
cube.surface.color = (0.8, 0.1 , 0.1)

cylinder_pos = (0.7, -0.2, 0.05)
cylinder_radius = 0.03
cylinder_height = 0.1

cylinder = scene.add_entity(
    gs.morphs.Cylinder(
        radius = cylinder_radius,
        height = cylinder_height,
        pos    = cylinder_pos,
    ),
    # surface=gs.textures.ColorTexture(
    #     color = (0.2, 0.8, 0.2),        
    # ),
)
cylinder.surface.color = (0.2, 0.8, 0.2)

cam = scene.add_camera(
    res    = (640, 480),
    pos    = (3.5, 0.0, 2.5),
    lookat = (0, 0, 0.5),
    fov    = 30,
    GUI    = False,
)


[Genesis] [10:33:13] [INFO] Scene <c635b54> created.
[Genesis] [10:33:13] [INFO] Adding <gs.RigidEntity>. idx: 0, uid: <66f8278>, morph: <gs.morphs.Plane>, material: <gs.materials.Rigid>.
[Genesis] [10:33:13] [INFO] Adding <gs.RigidEntity>. idx: 1, uid: <33204d1>, morph: <gs.morphs.MJCF(file='d:\envs\pygen\Lib\site-packages\genesis\assets\xml/franka_emika_panda/panda.xml')>, material: <gs.materials.Rigid>.
[Genesis] [10:33:16] [WARNING] (MJCF) Tendon not supported
[Genesis] [10:33:16] [WARNING] (MJCF) Approximating tendon by joint actuator for `finger_joint1`
[Genesis] [10:33:16] [WARNING] (MJCF) Actuator control gain and bias parameters cannot be reduced to a unique PD control position gain. Using max between gain and bias.
[Genesis] [10:33:16] [WARNING] (MJCF) Approximating tendon by joint actuator for `finger_joint2`
[Genesis] [10:33:16] [WARNING] (MJCF) Actuator control gain and bias parameters cannot be reduced to a unique PD control position gain. Using max between gain and bias.

In [4]:

scene.build()
motors_dof = np.arange(7)
fingers_dof = np.arange(7, 9)

# set control gains
# Note: the following values are tuned for achieving best behavior with Franka
# Typically, each new robot would have a different set of parameters.
# Sometimes high-quality URDF or XML file would also provide this and will be parsed.
franka.set_dofs_kp(
    np.array([4500, 4500, 3500, 3500, 2000, 2000, 2000, 100, 100]),
)
franka.set_dofs_kv(
    np.array([450, 450, 350, 350, 200, 200, 200, 10, 10]),
)
franka.set_dofs_force_range(
    np.array([-87, -87, -87, -87, -12, -12, -12, -100, -100]),
    np.array([ 87,  87,  87,  87,  12,  12,  12,  100,  100]),
)

# render rgb, depth, segmentation, and normal
# rgb, depth, segmentation, normal = cam.render(rgb=True, depth=True, segmentation=True, normal=True)


[Genesis] [10:33:18] [INFO] Building scene <c635b54>...
[Genesis] [10:33:22] [WARNING] Reference robot position exceeds joint limits.
[Genesis] [10:33:22] [WARNING] Constraint solver time constant was increased to avoid numerical instability (from `0.005` to `0.02`). Decrease simulation timestep to avoid altering the original value.
[Genesis] [10:33:42] [INFO] Compiling simulation kernels...
[Genesis] [10:38:46] [INFO] Building visualizer...
[Genesis] [10:38:51] [INFO] Viewer created. Resolution: 1280×960, max_FPS: 60.


In [5]:
# get cubes prperties
cube_pos = cube.get_pos()
print(f"cube_pos: {cube_pos}")
cube_rot = cube.get_quat()
print(f"cube_rot: {cube_rot}")
cube_mass = cube.get_mass()
print(f"cube_mass: {cube_mass}")
cube_vertices = cube.get_verts()
print(f"cube_vertices: {cube_vertices}")

cube_pos: tensor([0.7000, 0.0000, 0.0150])
cube_rot: tensor([1., 0., 0., 0.])
cube_mass: 0.04200000000000001
cube_vertices: tensor([[ 0.6500, -0.0350,  0.0000],
        [ 0.6500, -0.0350,  0.0300],
        [ 0.6500,  0.0350,  0.0000],
        [ 0.6500,  0.0350,  0.0300],
        [ 0.7500, -0.0350,  0.0000],
        [ 0.7500, -0.0350,  0.0300],
        [ 0.7500,  0.0350,  0.0000],
        [ 0.7500,  0.0350,  0.0300]])


In [6]:
cube.surface.get_rgba()

ColorTexture(color=(1.0, 1.0, 1.0, 1.0))

In [7]:
cube_pos = (0.7, 0, 0.015)
cube_qpos = np.concatenate((np.array(cube_pos), np.array([1, 0, 0, 0])), axis=0)
cube.set_qpos(cube_qpos)
qr = np.array([0.0000, -0.3002, 0.0000, -2.1991, 0.0000, 2.0071, 0.7854, 0.04, 0.04])

franka.ready_qpos = qr
franka.set_qpos(franka.ready_qpos)
scene.step()

[Genesis] [10:44:29] [INFO] Running at 0.06 FPS.


In [8]:
# get cylinder properties
cylinder_pos = cylinder.get_pos()
print(f"cylinder_pos: {cylinder_pos}")
cylinder_rot = cylinder.get_quat()
print(f"cylinder_rot: {cylinder_rot}")
cylinder_mass = cylinder.get_mass()
print(f"cylinder_mass: {cylinder_mass}")
# cylinder_vertices = cylinder.get_verts()
# print(f"cylinder_vertices: {cylinder_vertices}")

cylinder_pos: tensor([ 0.7000, -0.2000,  0.0490])
cylinder_rot: tensor([1., 0., 0., 0.])
cylinder_mass: 0.05618601274064494


In [9]:
cylinder.get_AABB()

tensor([[ 0.6700, -0.2300, -0.0010],
        [ 0.7300, -0.1700,  0.0990]])

In [10]:
# get cylinder Rotation matrix
R_initial = gs.quat_to_R(cylinder.get_quat())
R_initial = R_initial.numpy()
# now multiply this R by another given R to get the new rotation matrix
R =np.array([[0, 0, -1], [0, 1, 0], [1, 0, 0]])
R_goal = np.dot(R_initial, R)
quat_goal = gs.R_to_quat(R_goal)
quat_goal

array([-0.70710678,  0.        ,  0.70710678,  0.        ])

In [11]:
cylinder.get_quat()

tensor([1., 0., 0., 0.])

In [12]:
cylinder_pos = (0.7, -0.2, 0.05-0.02)
cyl_qpos = np.concatenate((np.array(cylinder_pos), quat_goal), axis=0)
cylinder.set_qpos(cyl_qpos)
scene.step()

[Genesis] [10:44:41] [INFO] Running at 0.06 FPS.


In [ ]:
vertices = cylinder.get_verts()
vertices = np.array(vertices)

max_x = np.max(vertices[:, 0])
min_y = np.min(vertices[:, 1])
min_z = np.min(vertices[:, 2])
max_y = np.max(vertices[:, 1])

v1 = np.array([max_x, min_y, min_z])  # max x, min y, min z
v2 = np.array([max_x, max_y, min_z])  # max x, max y, min z
v1

C:\Users\boroj\AppData\Local\Temp\ipykernel_21256\599004262.py:2: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  vertices = np.array(vertices)


array([ 0.7505875 , -0.23      , -0.00115065], dtype=float32)

In [14]:
v2

array([ 0.7505875 , -0.17      , -0.00115065], dtype=float32)

In [15]:
cylinder.get_AABB()

tensor([[ 0.6499, -0.2300, -0.0012],
        [ 0.7506, -0.1700,  0.0600]])

In [16]:
cylinder.get_pos()

tensor([ 0.7003, -0.2000,  0.0294])

In [ ]:
def get_obj_screw(object):
    """
    Get the screw parameters of the object
    """
    # get the vertices of the object
    vertices = object.get_verts()
    vertices = vertices.numpy()

    # get the max and min x, y, z coordinates
    max_x = np.max(vertices[:, 0])
    min_x = np.min(vertices[:, 0])
    min_y = np.min(vertices[:, 1])
    min_z = np.min(vertices[:, 2])
    max_y = np.max(vertices[:, 1])
    
    v1 = np.array([max_x, min_y, min_z])  # max x, min y, min z
    v2 = np.array([max_x, max_y, min_z])  # max x, max y, min z
    v3 = np.array([min_x, max_y, min_z])  # min x, max y, min z
    
    if np.linalg.norm(v1-v2) <= np.linalg.norm(v2-v3):
        s = (v1-v2) / np.linalg.norm(v1-v2) # unit vector in the direction of the screw axis
        q = v2 # point on the screw axis
        h = 0 # pitch of the screw axis
    else:
        s = (v2-v3) / np.linalg.norm(v2-v3) # unit vector in the direction of the screw axis
        q = v2 # point on the screw axis
        h = 0 # pitch of the screw axis
    
    pt.check_screw_parameters(q, s, h) # check if the screw parameters are valid
    return s, q, h


In [144]:
def obj_dq(object):
    """
    Get the screw parameters of the object and apply sclerp to the object in dual quaternion
    """
    # get the screw parameters of the object
    s, q, h = get_obj_screw(object)
    
    pq = object.get_qpos().cpu().numpy()

    obj_initial_dq = pt.dual_quaternion_from_pq(pq) # dual quaternion from position and quaternion
    
    Screw_dq = pt.dual_quaternion_from_screw_parameters(q=q, s_axis=s, h=0, theta=-np.pi/2) # dual quaternion from screw parameters that make the object upright
    intermediate_T = pt.transform_log_from_screw_matrix
    Screw_T = pt.transform_from_dual_quaternion(Screw_dq) # transform from dual quaternion to transformation matrix
    print("screw_dq: \n", Screw_dq)
    print("screw_T: \n", Screw_T)
    obj_goal_dq = pt.concatenate_dual_quaternions(Screw_dq, obj_initial_dq)
    obj_goal_T = pt.transform_from_dual_quaternion(obj_goal_dq) # transform from dual quaternion to transformation matrix
    print("obj_goal_dq: \n", obj_goal_dq)
    print("obj_goal_T: \n", obj_goal_T)
    return obj_initial_dq, obj_goal_dq

In [ ]:
def obj_sclerp(object, obj_initial_dq, obj_goal_dq, method, steps):
    """
    Apply sclerp to the object in dual quaternion
    """
    s = np.linspace(0, 1, steps)
    if method == 'linear':
        tau = s
    if method == 'cubic':
        tau = 3*s**2 - 2*s**3
    if method == 'quintic':
        tau = 10*s**3 - 15*s**4 + 6*s**5
        
    # get the dual quaternion of the object
    dq_traj = np.vstack(
            [ptr.dual_quaternions_sclerp(obj_initial_dq, obj_goal_dq, t) for t in tau]
        )  # spherical linear interpolation between two dual quaternions
    # get the position and quaternion from the dual quaternion
    obj_qpos = ptr.pqs_from_dual_quaternions(dq_traj)
    
    return dq_traj, obj_qpos

In [92]:
scene.reset()

[Genesis] [12:09:41] [INFO] Resetting Scene <c635b54>.


In [ ]:
s = np.array([0.75, 0, 0]) # screw axis


In [131]:
cube.get_pos()

tensor([0.7000, 0.0000, 0.0150])

In [136]:
q 

array([0.75 , 0.035, 0.   ], dtype=float32)

In [140]:
T1 = pt.transform_from_dual_quaternion(obj_initial_dq)

In [138]:
Screw_dq = pt.dual_quaternion_from_screw_parameters(q=q, s_axis=s, h=0, theta=-np.pi/2)
T2 = pt.transform_from_dual_quaternion(Screw_dq)
print(T2)

[[-2.22044605e-16  0.00000000e+00  1.00000000e+00  7.50000000e-01]
 [-0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.00000000e+00 -0.00000000e+00 -2.22044605e-16  7.50000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [143]:
print(T2@T1)

[[-2.22044605e-16  0.00000000e+00  1.00000000e+00  7.65000000e-01]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.00000000e+00  0.00000000e+00 -2.22044605e-16  5.00000119e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [142]:
print(T1@T2)

[[-2.22044605e-16  0.00000000e+00  1.00000000e+00  1.44999999e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.00000000e+00  0.00000000e+00 -2.22044605e-16  7.65000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [145]:
# calling functions
scene.reset()
s, q, h = get_obj_screw(cube)

obj_initial_dq, obj_goal_dq = obj_dq(cube)
dq_traj, obj_qpos = obj_sclerp(cube, obj_initial_dq, obj_goal_dq, 'linear', 100)
dq_traj.shape[0]

[Genesis] [13:09:33] [INFO] Resetting Scene <c635b54>.
screw_dq: 
 [ 0.70710678 -0.          0.70710678 -0.         -0.         -0.
  0.          0.53033009]
screw_T: 
 [[-2.22044605e-16  0.00000000e+00  1.00000000e+00  7.50000000e-01]
 [-0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.00000000e+00 -0.00000000e+00 -2.22044605e-16  7.50000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
obj_goal_dq: 
 [0.70710678 0.         0.70710678 0.         0.         0.25279067
 0.         0.28814602]
obj_goal_T: 
 [[-2.22044605e-16  0.00000000e+00  1.00000000e+00  7.65000000e-01]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.00000000e+00  0.00000000e+00 -2.22044605e-16  5.00000119e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


100

In [125]:
h

0

In [148]:
scene.reset()
for i in range (obj_qpos.shape[0]):
    franka.set_qpos(qr)
    cube.set_qpos(obj_qpos[i])
    scene.step()


[Genesis] [13:10:24] [INFO] Resetting Scene <c635b54>.
[Genesis] [13:10:24] [INFO] Running at 1.54 FPS.
[Genesis] [13:10:24] [INFO] Running at 1.61 FPS.
[Genesis] [13:10:24] [INFO] Running at 1.70 FPS.
[Genesis] [13:10:24] [INFO] Running at 1.78 FPS.
[Genesis] [13:10:24] [INFO] Running at 1.87 FPS.
[Genesis] [13:10:24] [INFO] Running at 1.96 FPS.
[Genesis] [13:10:24] [INFO] Running at 2.06 FPS.
[Genesis] [13:10:24] [INFO] Running at 2.17 FPS.
[Genesis] [13:10:24] [INFO] Running at 2.27 FPS.
[Genesis] [13:10:24] [INFO] Running at 2.38 FPS.
[Genesis] [13:10:24] [INFO] Running at 2.50 FPS.
[Genesis] [13:10:24] [INFO] Running at 2.62 FPS.
[Genesis] [13:10:24] [INFO] Running at 2.74 FPS.
[Genesis] [13:10:24] [INFO] Running at 2.88 FPS.
[Genesis] [13:10:24] [INFO] Running at 3.01 FPS.
[Genesis] [13:10:24] [INFO] Running at 3.16 FPS.
[Genesis] [13:10:24] [INFO] Running at 3.31 FPS.
[Genesis] [13:10:24] [INFO] Running at 3.46 FPS.
[Genesis] [13:10:24] [INFO] Running at 3.61 FPS.
[Genesis] [13:

In [51]:
s,q,h = get_obj_screw(cylinder)

In [55]:
pos = cylinder.get_pos().cpu().numpy() 
quat = cylinder.get_quat().cpu().numpy() 
    
# Concatenate into a single array
pq = np.concatenate([pos, quat])
obj_dq = pt.dual_quaternion_from_pq(pq) # dual quaternion from position and quaternion

In [ ]:
screw_dq = pt.dual_quaternion_from_screw_parameters(s, q, h, np.pi/2) # dual quaternion from screw parameters
pt.dual_quaternion_sclerp

<function pytransform3d.transformations._dual_quaternion.dual_quaternion_sclerp(start, end, t)>

In [59]:
pt.concatenate_dual_quaternions(obj_dq, screw_dq)

array([-0.39297261, -0.49112069,  0.60825131, -0.48415219,  0.23989887,
        0.38603317,  0.20159041, -0.33304596])

In [32]:
end_effector = franka.get_link('hand')
left_finger = franka.get_link('left_finger')
right_finger = franka.get_link('right_finger')

left_finger.get_pos(), right_finger.get_pos(), end_effector.get_pos()

(tensor([ 0.4585, -0.0406,  0.3952]),
 tensor([0.4582, 0.0394, 0.3948]),
 tensor([ 4.5857e-01, -2.7521e-04,  4.5343e-01]))

In [33]:

# get the end-effector link
end_effector = franka.get_link('hand')
above_box = cube.get_pos().cpu().numpy() + np.array([-cube_size[0]/2 + 0.02, 0, 0.11 + 0.1])
# move to pre-grasp pose
qpos = franka.inverse_kinematics(
    link = end_effector,
    pos  = above_box,
    quat = np.array([0, 1, 0, 0]),
)
# # gripper open pos
# qpos[-2:] = 0.04
# path = franka.plan_path(
#     qpos_goal     = qpos,
#     num_waypoints = 200, # 2s duration
# )

In [ ]:
franka.get_qpos(), qpos

# find straight path in joint space
s = np.linspace(0, 1, 200)
current_pose = franka.get_qpos().cpu().numpy()
goal_pos = qpos.cpu().numpy()
path = current_pose + s[:, None] * (goal_pos - current_pose)


In [ ]:
for qpos in path:
    # set qpos
    franka.control_dofs_position(qpos)
    # step simulation
    scene.step()

In [ ]:
qpos

In [ ]:
# # execute the planned path
# for waypoint in path:
#     franka.control_dofs_position(waypoint)
#     scene.step()

# allow robot to reach the last waypoint
for i in range(100):
    scene.step()


In [ ]:
side_box = above_box + np.array([0.0, 0.0, -0.1])


# reach
qpos_reach = franka.inverse_kinematics(
    link = end_effector,
    pos  = side_box,
    quat = np.array([0, 1, 0, 0]),
)
# path = franka.plan_path(
#     qpos_goal     = qpos_reach,
#     num_waypoints = 100, # 1s duration
# )

# for waypoint in path:
franka.control_dofs_position(qpos_reach)
    # scene.step()

# allow robot to reach the last waypoint
for i in range(100):
    scene.step()

In [ ]:



# grasp
franka.control_dofs_position(qpos_reach[:-2], motors_dof)
franka.control_dofs_force(np.array([-0.5, -0.5]), fingers_dof)

for i in range(100):
    scene.step()


In [ ]:

# lift
qpos = franka.inverse_kinematics(
    link=end_effector,
    pos=np.array([0.65, 0.0, 0.28]),
    quat=np.array([0, 1, 0, 0]),
)
franka.control_dofs_position(qpos[:-2], motors_dof)
for i in range(200):
    scene.step()

In [ ]:
# open
qpos = franka.inverse_kinematics(
    link=end_effector,
    pos=np.array([0.65, 0.0, 0.28]),
    quat=np.array([0, 1, 0, 0]),
)

franka.control_dofs_position(qpos[:-2], motors_dof)
franka.control_dofs_force(np.array([0, 0]), fingers_dof)
for i in range(100):
    scene.step()
# allow robot to reach the last waypoint
for i in range(100):
    scene.step()

In [ ]:
franka.get_dofs_force()

In [ ]:
cube_pos = cube.get_pos().cpu().numpy()
cube_quat = cube.get_quat().cpu().numpy()

cube_pos, cube_quat

In [ ]:
cube_pos = cube.get_pos().cpu().numpy()
cube_quat = cube.get_quat().cpu().numpy()

qpos = franka.inverse_kinematics(
    link=end_effector,
    pos=cube_pos + np.array([0, 0, 0.3]),
    quat=np.array([0, 1, 0, 0]),
)

franka.control_dofs_position(qpos[:-2], motors_dof)
franka.control_dofs_force(np.array([0, 0]), fingers_dof)
for i in range(100):
    scene.step()
# allow robot to reach the last waypoint
for i in range(100):
    scene.step()

In [ ]:

cam.start_recording()
import numpy as np

for i in range(120):
    scene.step()
    cam.set_pose(
        pos    = (3.0 * np.sin(i / 60), 3.0 * np.cos(i / 60), 2.5),
        lookat = (0, 0, 0.5),
    )
    cam.render()
cam.stop_recording(save_to_filename='video.mp4', fps=60)